import { Candidate, SelectionProcess, Vacancy } from "@legacy/types/models";

const FIXED_DATE = new Date("2026-01-01T00:00:00.000Z");

export const sampleCandidates: Candidate[] = [
  {
    id: "C-2024-0451",
    fullName: "Maria Gonzalez",
    email: "maria.gonzalez@email.com",
    phone: "+56912345678",
    yearsOfExperience: 5,
    skills: ["TypeScript", "React", "Node.js", "PostgreSQL"],
    englishLevel: "B2",
    seniority: "Semi-Senior",
    currentSalary: 3500,
    expectedSalary: 4200,
    availability: "1 month",
    location: "Valencia, Espana",
    remoteOnly: false,
    status: "Active",
  },
  {
    id: "C-2024-0452",
    fullName: "Juan Perez",
    email: "juan.perez@email.com",
    phone: "+56987654321",
    yearsOfExperience: 3,
    skills: ["JavaScript", "React", "CSS", "HTML"],
    englishLevel: "B1",
    seniority: "Junior",
    currentSalary: 2200,
    expectedSalary: 2800,
    availability: "Immediate",
    location: "Miami, Florida, Estados Unidos",
    remoteOnly: true,
    status: "Active",
  },
  {
    id: "C-2024-0453",
    fullName: "Carolina Silva",
    email: "carolina.silva@email.com",
    phone: "+56911223344",
    yearsOfExperience: 8,
    skills: ["TypeScript", "Node.js", "PostgreSQL", "Docker", "AWS"],
    englishLevel: "C1",
    seniority: "Senior",
    currentSalary: 5500,
    expectedSalary: 6500,
    availability: "2 weeks",
    location: "Valencia, Espana",
    remoteOnly: false,
    status: "Active",
  },
];

export const sampleVacancy: Vacancy = {
  id: "V-2024-0892",
  title: "Senior Full-Stack Developer",
  companyName: "Nexova Client",
  requiredSkills: ["TypeScript", "Node.js", "PostgreSQL"],
  preferredSkills: ["Docker", "AWS", "React"],
  minYearsExperience: 4,
  maxYearsExperience: 8,
  requiredEnglishLevel: "B2",
  requiredSeniority: "Senior",
  salaryRangeMin: 5000,
  salaryRangeMax: 6500,
  isRemote: false,
  location: "Valencia, Espana",
  status: "Open",
};

export const sampleProcesses: SelectionProcess[] = [
  {
    id: "SP-1",
    candidateId: "C-2024-0451",
    vacancyId: "V-2024-0892",
    stage: "Interview",
    score: 72,
    notes: "",
    createdAt: FIXED_DATE,
    updatedAt: FIXED_DATE,
  },
  {
    id: "SP-2",
    candidateId: "C-2024-0452",
    vacancyId: "V-2024-0892",
    stage: "Rejected",
    score: 54,
    notes: "",
    createdAt: FIXED_DATE,
    updatedAt: FIXED_DATE,
  },
  {
    id: "SP-3",
    candidateId: "C-2024-0453",
    vacancyId: "V-2024-0892",
    stage: "Hired",
    score: 93,
    notes: "",
    createdAt: FIXED_DATE,
    updatedAt: FIXED_DATE,
  },
];
